#ifndef KORTINLUKUDLL_GLOBAL_H
#define KORTINLUKUDLL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(KORTINLUKUDLL_LIBRARY)
#define KORTINLUKUDLL_EXPORT Q_DECL_EXPORT
#else
#define KORTINLUKUDLL_EXPORT Q_DECL_IMPORT
#endif

#endif // KORTINLUKUDLL_GLOBAL_H
